import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
// @ts-ignore: side-effect CSS import for global styles (Next.js)
import "./globals.css";

import Image from "next/image";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="flex flex-row items-center w-full min-h-screen space-between">
          <div className="w-1/5 min-w-64 h-[90vh] mr-10">
            <main className="relative w-full h-full p-4 overflow-hidden text-center bg-neutral-600 rounded-r-2xl">
              <div className="flex items-center justify-center w-full">
                <div className="relative w-[200px] h-[270px]">
                  <Image
                    src="/face.png"
                    alt="Its Me Image"
                    fill
                    sizes="400px"
                    className="object-cover rounded-xl border-2 border-neutral-300/10"
                  />
                </div>
              </div>
              <div>
                <h1 className="text-2xl font-bold">Rafał Curzydło</h1>
                <h2 className="text-lg font-medium">FrontEnd Developer</h2>
              </div>
              <div className="w-[90%] text-left p-5">
                <p className="mt-2 font-medium">
                  Age: <span>21</span>
                </p>
                <p className="mt-2 font-medium">
                  From: <span>Poland</span>
                </p>
              </div>
            </main>
          </div>
          <div className="w-full h-[90vh] rounded-l-2xl overflow-hidden">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
