import type { Metadata } from "next";
import { Geist } from "next/font/google";
// @ts-ignore: side-effect CSS import for global styles (Next.js)
import "./globals.css";
import NavInformation from "@/components/NavInformation";

import Image from "next/image";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist({
  variable: "--font-geist-mono",
  subsets: ["latin"],
  style: "normal",
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const categories = ["About Me", "Skills", "Projects", "Contact"];

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="flex flex-row items-center w-full min-h-screen space-between">
          <div className="w-1/5 min-w-64 h-[90vh] mr-10">
            <main className="relative w-full h-full p-4 overflow-hidden text-center bg-neutral-600 rounded-r-2xl">
              <div className="flex items-center justify-center w-full">
                <div className="relative w-[200px] h-[270px]">
                  <Image
                    src="/face.png"
                    alt="Its Me Image"
                    fill
                    sizes="400px"
                    className="object-cover rounded-xl border-2 border-neutral-300/10"
                  />
                </div>
              </div>
              <div>
                <h1 className="text-2xl font-bold">Rafał Curzydło</h1>
                <h2 className="text-lg font-medium">FrontEnd Developer</h2>
              </div>
              <div className="w-[90%] text-left p-5 flex flex-col h-full space-y-5">
                <NavInformation img={"/github.png"}>GitHub</NavInformation>
                <NavInformation img={"/linkedin.png"}>LinkedIn</NavInformation>
              </div>
            </main>
          </div>
          <div className="w-full h-[90vh] flex justify-start items-start rounded-l-2xl overflow-hidden dark:bg-neutral-600">
            <div className="flex flex-row absolute right-0 border-2 rounded-bl-2xl border-neutral-700 overflow-hidden ">
              {categories.map((category) => (
                <Link
                  href={`${category}`}
                  key={category}
                  className="px-4 py-1 hover:bg-neutral-700 hover:font-bold border-r-2 border-neutral-700 hover:cursor-pointer"
                >
                  {category}
                </Link>
              ))}
            </div>
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
