import type { Metadata } from "next";
import { Geist } from "next/font/google";
// @ts-ignore: side-effect CSS import for global styles (Next.js)
import "./globals.css";
import NavInformation from "@/components/nav-information";

import Image from "next/image";
import MobileMenu from "../components/mobile-menu";
import MenuLinks from "../components/menu-links";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist({
  variable: "--font-geist-mono",
  subsets: ["latin"],
  style: "normal",
  weight: "400",
});

export const metadata: Metadata = {
  title: "Rafał Curzydło",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="fixed w-full border-b-4 rounded-b-lg sm:hidden h-15 bg-neutral-600 border-neutral-700">
          <MobileMenu />
        </div>
        <div className="flex flex-row items-center w-full min-h-screen pt-5 bg-black sm:pt-0 space-between">
          <div className="w-1/5 hidden sm:flex min-w-64 h-[90vh] mr-10">
            <main className="relative w-full h-full p-4 overflow-hidden text-center bg-neutral-600 rounded-r-2xl">
              <div className="flex items-center justify-center w-full">
                <div className="relative w-50 h-67.5 bg-linear-to-br from-orange-700 to-orange-400 rounded-xl">
                  <Image
                    src="/face.png"
                    alt="Its Me Image"
                    fill
                    sizes="400px"
                    className="object-cover p-1 border-2 rounded-xl"
                  />
                </div>
              </div>
              <div>
                <h1 className="text-2xl font-bold">Rafał Curzydło</h1>
                <h2 className="text-lg font-medium text-orange-300">
                  FrontEnd Developer
                </h2>
              </div>
              <div className="w-[90%] text-left p-5 flex flex-col h-full space-y-5">
                <NavInformation img={"/github.png"}>GitHub</NavInformation>
                <NavInformation img={"/linkedin.png"}>LinkedIn</NavInformation>
              </div>
            </main>
          </div>
          <div className="flex w-full h-[90vh] justify-start items-start rounded-xl sm:rounded-r-none sm:rounded-l-2xl overflow-hidden border-t-4 border-neutral-700">
            <div className="hidden sm:flex flex-row absolute right-0 top-[15] border-b-0 border-2 rounded-tl-2xl border-neutral-700 bg-neutral-600 overflow-hidden h-8">
              <MenuLinks />
            </div>
            <div className="flex flex-col items-center justify-start w-full h-full gap-10 px-0 py-5 overflow-y-auto font-sans bg-neutral-600">
              <div className="flex flex-col items-start justify-start gap-10 px-5">
                {children}
              </div>
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
